### ISSUE TITLE
Improve Snap UI with asset names, market names and decimal places

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega-snap#15]
Transaction views currently only show the raw transaction data which can be confusing for most users. This ticket is to improve the ui by showing more useful data where possible. For example

- [ ] Instead of market IDs show the market code or name
- [ ] Instead of asset IDs show the asset name/symbol
- [ ] Where we show balances, positions, prices etc show correctly converted values (using asset.decimals or market.decimalPlaces or market.positionDecimalPlaces)
- [ ] Work out where in the snap we can stash a link to move people onto Vega Wallet

**Comment by JonRay15** [comment]
- Add caching of markets and assets when we load up the snap
- Add a timeout to make sure you can load
- If you havent been able to load by then show the unenriched view with some warning message saying we've been unable to do this and so you will see market / asset codes and unconverted price / size numbers.
